spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:accounttestdb
        driverClassName: org.h2.Driver
        username: h2
        password: 123
    jpa: 
        hibernate: 
            ddl-auto: create
    mail:
        host: sandbox.smtp.mailtrap.io
        port: 2525
        username: d0e7b7cee9d368
        password: 7eec3f7f63d027
        properties:
            mail: 
                smtp:
                    auth: true
                    starttls: 
                        enable: true
token:
    algorithm: AES
    secretKey: scepticalAlienss